#!/bin/bash


aslfile="$1"
astfile="$aslfile".lsp
outfile="$aslfile".out

if ! ( aslref --print-lisp --no-exec "$aslfile" > "$astfile" ); then
    echo "aslref error"
    exit 1;
fi

echo "(assign :fname \"$astfile\") (ld \"run-test.lsp\")" | acl2 > "$outfile"

start_pattern='!@#$%^%$#@ begin ASL interpreter output'
end_pattern='!@#$%^%$#@ end ASL interpreter output'

if ! ( fgrep -q "$start_pattern" "$outfile" > /dev/null &&
	   fgrep -q "$end_pattern" "$outfile" > /dev/null ) then
   echo "ACL2 failed to run ASL interpretation"
   exit 1;
fi

# generated by chatgpt
awk -v start="$start_pattern" -v end="$end_pattern" '
    index($0, start) {flag=1; next} 
    index($0, end) && flag {exit} 
    flag { printf "%s", sep $0; sep=ORS }' "$outfile"

