#!/bin/bash


aslfile="$1"
astfile="$aslfile".lsp
outfile="$aslfile".out

aslref --print-lisp --no-exec "$aslfile" > "$astfile"

echo "(assign :fname \"$astfile\") (ld \"run-test.lsp\")" | acl2 > "$outfile"


start_pattern='!@#$%^%$#@ begin ASL interpreter output'
end_pattern='!@#$%^%$#@ end ASL interpreter output'

# generated by chatgpt
awk -v start="$start_pattern" -v end="$end_pattern" '
    index($0, start) {flag=1; next} 
    index($0, end) && flag {exit} 
    flag { printf "%s", sep $0; sep=ORS }' "$outfile"

